// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZAZo6TLH2bbHCq0XUwM6Pogavi6FyrGk',
    appId: '1:350212176095:web:c41cf8063e071c2ebb516a',
    messagingSenderId: '350212176095',
    projectId: 'flash-card-ac557',
    authDomain: 'flash-card-ac557.firebaseapp.com',
    databaseURL: 'https://flash-card-ac557-default-rtdb.firebaseio.com',
    storageBucket: 'flash-card-ac557.firebasestorage.app',
    measurementId: 'G-XCQKJCVV0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSp3e6flbzviw9y3ZVc1_VxRYtMfCsOTE',
    appId: '1:350212176095:android:f6852b14548a172fbb516a',
    messagingSenderId: '350212176095',
    projectId: 'flash-card-ac557',
    databaseURL: 'https://flash-card-ac557-default-rtdb.firebaseio.com',
    storageBucket: 'flash-card-ac557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA17YRWdoatL4IbvvMzEt5zY9yVcQPPfzY',
    appId: '1:350212176095:ios:2c3b6fac7ee6bce3bb516a',
    messagingSenderId: '350212176095',
    projectId: 'flash-card-ac557',
    databaseURL: 'https://flash-card-ac557-default-rtdb.firebaseio.com',
    storageBucket: 'flash-card-ac557.firebasestorage.app',
    iosBundleId: 'com.example.flashCardAss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA17YRWdoatL4IbvvMzEt5zY9yVcQPPfzY',
    appId: '1:350212176095:ios:2c3b6fac7ee6bce3bb516a',
    messagingSenderId: '350212176095',
    projectId: 'flash-card-ac557',
    databaseURL: 'https://flash-card-ac557-default-rtdb.firebaseio.com',
    storageBucket: 'flash-card-ac557.firebasestorage.app',
    iosBundleId: 'com.example.flashCardAss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZAZo6TLH2bbHCq0XUwM6Pogavi6FyrGk',
    appId: '1:350212176095:web:ff5f0470668016febb516a',
    messagingSenderId: '350212176095',
    projectId: 'flash-card-ac557',
    authDomain: 'flash-card-ac557.firebaseapp.com',
    databaseURL: 'https://flash-card-ac557-default-rtdb.firebaseio.com',
    storageBucket: 'flash-card-ac557.firebasestorage.app',
    measurementId: 'G-H9JR4RLWSL',
  );
}
